# Generated by Django 5.2.5 on 2025-08-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='commentary',
            field=models.TextField(blank=True, verbose_name='Commentary'),
        ),
    ]
