# Generated by Django 5.2.5 on 2025-08-07 13:31

import critic_chords.reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_commentary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[critic_chords.reviews.validators.validate_rating], verbose_name='Rating'),
        ),
    ]
