# Generated by Django 5.2.5 on 2025-08-07 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_album_about'),
        ('reviews', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='albums.album'),
        ),
    ]
