# Generated by Django 5.2.5 on 2025-08-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_options_alter_artist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_art',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Cover Art'),
        ),
    ]
