# Generated by Django 5.2.5 on 2025-08-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_album_cover_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='about',
            field=models.TextField(default='', verbose_name='About'),
            preserve_default=False,
        ),
    ]
