# Generated by Django 5.2.5 on 2025-08-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_album_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='overall_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Overall Rating'),
        ),
    ]
