# Generated by Django 5.2.5 on 2025-08-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_album_overall_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='overall_rating',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Overall Rating'),
        ),
    ]
